###

GET http://localhost:7070/users HTTP/1.1

###

GET http://localhost:7070/users/5ec5cb85e2a5aa79c249eacc HTTP/1.1

###
POST http://localhost:7070/users HTTP/1.1
content-type: application/json

{
    "usr" : {"name" : "Javier", "lastname" : "Lopez"},
    "email" : "stalynJvier@gmail.com",
    "pwd" : "apiRest1",   
    "permissionLevel": "2" 
}

###

GET http://localhost:7070/users HTTP/1.1

###

PATCH  http://localhost:7070/users/5ee2cee3a249271400263da8 HTTP/1.1
content-type: application/json

{
  "usr" : {"name" : "Javier", "lastname" : "Chancay"},
  "email" : "stalynJvier@hotmail.com",
  "pwd" : "forEverAlone",   
  "permissionLevel": "2" 
}

###

GET http://localhost:7070/users HTTP/1.1

###

POST http://localhost:7070/users HTTP/1.1
content-type: application/json

{
    "usr" : {"name" : "Rosa", "lastname" : "Lopez"},
    "email" : "Rosa.suarez@gmail.com",
    "pwd" : "Dontseeme",   
    "permissionLevel": "2" 
}

###
DELETE http://localhost:7070/users/5ee2cdc713bd6813b0b227c2 HTTP/1.1

###

GET http://localhost:7070/users HTTP/1.1

###

POST http://localhost:7070/users HTTP/1.1
Content-Type: application/xml

<request>
    <usr><name>Rosa</name> <lastname>Lopez</lastname></usr>
    <email>Rosa.suarez@gmail.com</email>
    <pwd>dontseeme</pwd>   
    <permissionLevel>2</permissionLevel>
</request>